#!/bin/bash

echo "=========================="
echo "GitLab 仓库备份工具日志测试"
echo "=========================="
echo ""

echo "测试传统模式备份并提取分支代码（详细日志）："
echo "./back -b"
echo ""

echo "测试优化模式备份并提取分支代码（详细日志）："
echo "./back -b -o"
echo ""

echo "测试只提取已有仓库的分支代码（详细日志）："
echo "./back -e"
echo ""

echo "现在程序会显示以下详细日志信息："
echo ""
echo "传统模式 (extractAllBranches)："
echo "- 开始处理分支 X/Y: 分支名"
echo "- 正在提取分支 XXX 的代码到 路径"
echo "- ✓ 成功提取分支 XXX 的代码 (X/Y 完成)"
echo "- 分支代码提取完成: 成功 X/Y 个分支"
echo ""
echo "优化模式 (extractBranchesOptimized)："
echo "- 开始处理分支 X/Y: 分支名" 
echo "- 正在checkout分支: 分支名"
echo "- ✓ 成功checkout分支: 分支名 (X/Y)"
echo "- 分支checkout统计: 成功 X/Y 个分支, 获得信息 Z 个分支"
echo ""
echo "快照创建 (createBranchSnapshot)："
echo "- 正在checkout分支用于快照创建: 分支名"
echo "- ✓ 成功checkout分支用于快照: 分支名"
echo ""
echo "选择性分支备份 (extractSelectedBranches)："
echo "- 开始为 X 个指定分支创建代码快照"
echo "- 创建分支快照 X/Y: 分支名"
echo "- ✓ 成功创建分支 XXX 的代码快照 (X/Y)"
echo "- 分支快照创建完成: 成功 X/Y 个分支"
echo ""

echo "更新日志特性："
echo "1. 显示当前处理的分支序号和总数 (X/Y)"
echo "2. 使用 ✓ 和 ✗ 符号标识成功和失败"
echo "3. 显示详细的Git命令输出（失败时）"
echo "4. 统计成功和失败的分支数量"
echo "5. 为每个checkout操作添加专门的日志记录"
echo "6. 显示文件保存路径等详细信息"